In [15]:
# import essential Libraries
import numpy as np
import pandas as pd

In [16]:
#Acquire DataSet
df=pd.read_csv("dataset.csv")
df

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [17]:
df.shape

(1461, 6)

In [18]:
df2=df.drop("date",axis=1)
df2.head()

precipitation  temp_max  temp_min  wind  weather
0            0.0      12.8       5.0   4.7  drizzle
1           10.9      10.6       2.8   4.5     rain
2            0.8      11.7       7.2   2.3     rain
3           20.3      12.2       5.6   4.7     rain
4            1.3       8.9       2.8   6.1     rain

In [19]:
df2.shape #number of row-1461 and number of column=5

(1461, 5)

# separating dataset into independent and dependent variable by using iloc functions

In [20]:
X=df2.iloc[:,:4].values
X

array([[ 0. , 12.8,  5. ,  4.7],
       [10.9, 10.6,  2.8,  4.5],
       [ 0.8, 11.7,  7.2,  2.3],
       ...,
       [ 0. ,  7.2,  0.6,  2.6],
       [ 0. ,  5.6, -1. ,  3.4],
       [ 0. ,  5.6, -2.1,  3.5]])

In [21]:
Y=df2.iloc[:,4].values
Y

array(['drizzle', 'rain', 'rain', ..., 'fog', 'sun', 'sun'], dtype=object)

# Spliting dataset into training and testing dataset

In [33]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

# Applying Logistic Algorithm 

In [32]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)

C:\Users\vinay\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

# Testing the Model

In [34]:
y_pred=lr.predict(x_test)
y_pred

array(['sun', 'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'rain', 'sun',
       'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'rain', 'rain', 'rain', 'rain', 'sun', 'sun', 'sun', 'sun',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'rain', 'sun', 'rain',
       'sun', 'rain', 'sun', 'rain', 'sun', 'rain', 'rain', 'rain', 'sun',
       'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain',
       'rain', 'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun',
       'sun', 'sun', 'rain', 'sun', 'sun', 'sun', 'rain', 'rain', 'rain',
       'rain', 'sun', 'sun', 'sun', 'sun', 'sun', 'rain', 'rain', 'sun',
       'sun', 'rain', 'rain', 'rain', 'sun', 'sun', 'rain', 'sun', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'snow', 'sun', 'sun', 'sun',
       'sun', 'rain', 'sun', 'sun', 'rain', 'rain', 'sun', 'rain', 'rain',
       'sun', 'sun', 'rain', 'sun', 'rain', 'sun', 'sun', 'sun', 'sun',
       'sun', 'rain', 'rain', 'sun', 'rain

In [28]:
x_test

array([[ 0. , 20. , 12.2,  3.7],
       [ 0. , 10.6,  7.8,  1.4],
       [ 8.4, 14.4, 10. ,  3. ],
       [ 0. , 23.9,  7.8,  5.1],
       [ 0. , 12.8,  7.2,  1.2],
       [19.6, 12.8,  6.7,  5.5],
       [ 1.3, 11.7,  7.8,  2.3],
       [ 4.3, 21.7, 14.4,  2.5],
       [ 0. , 20.6,  8.3,  2.2],
       [ 1. , 13.3,  4.4,  5.1],
       [ 0. , 30. , 16.7,  4.4],
       [12.2,  8.3,  5. ,  1.6],
       [ 0. , 21.1, 14.4,  2.4],
       [ 0. , 26.1, 16.7,  2.2],
       [ 0. , 19.4,  9.4,  1.8],
       [ 0. , 20. ,  8.9,  4.2],
       [ 0. , 25. , 14.4,  3.7],
       [ 5.6,  9.4,  5. ,  4.7],
       [13.5,  8.9,  3.3,  2.7],
       [ 1. , 15. ,  9.4,  5.2],
       [ 6.1, 12.8,  8.9,  4.8],
       [ 7.4, 11.1,  5. ,  4. ],
       [ 8.6, 10. ,  2.8,  5.9],
       [ 0. , 28.9, 15. ,  3.3],
       [ 0. , 27.8, 13.3,  1.9],
       [ 0. , 24.4, 14.4,  4.4],
       [ 0. , 18.3,  9.4,  2.7],
       [ 2.8,  8.9,  6.1,  1.6],
       [ 0. , 23.3, 12.2,  1.9],
       [ 0. , 17.2,  5. ,  2.8],
       [ 0

# Building confusion matrix 
to compare real and predicted values

In [24]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 0,  0,  0,  0,  5],
       [ 0,  0,  0,  0, 12],
       [ 0,  0, 60,  0,  8],
       [ 0,  0,  1,  1,  0],
       [ 0,  0,  0,  0, 60]])

In [12]:
y_test.size

147

# Pickle file is used to store our modele which is used to deploye our model

In [25]:
import pickle

In [26]:
pickle.dump(lr,open('rfp.pkl','wb'))